# Change these first
owner: NeilDevelopment # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Neil Development
    url: https://neildevelopment.xyz
  - name: Paste
    url: https://paste.neildevelopment.xyz
  - name: CDN
    url: https://cdn.neildevelopment.xyz


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: NeilDevelopments GitHub status
  introTitle: "**Neil Development's GitHub Status**"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
